// Pure stack compiler: Stack → ordered wslc-run plan + docker-compose export
// (decision D1: the app sequences documented commands, inventing none).

import { stringify as yamlStringify } from "@std/yaml";
import { buildRunArgs } from "../adapter/wslc.ts";
import type { Stack } from "./schema.ts";

export interface PlanStep {
  service: string;
  container: string;
  image: string;
  args: string[];
  preview: string;
}

/** A stack's containers are "<stack>-<service>". A single-workload Kubernetes import
 * names both after the same metadata.name, which would double it ("web-web"); collapse
 * that case. Only affects stacks deployed from now on — StackRecord stores the resolved
 * container name, so existing records still resolve for down/delete. */
export function containerNameFor(stackName: string, service: string): string {
  return service === stackName ? stackName : `${stackName}-${service}`;
}

/** Ordered execution plan — one documented `wslc run` per service. */
export function compilePlan(stack: Stack): PlanStep[] {
  return Object.entries(stack.services).map(([service, spec]) => {
    const container = containerNameFor(stack.name, service);
    const args = buildRunArgs({
      image: spec.image,
      name: container,
      ports: spec.ports,
      detach: spec.detach,
      rm: spec.rm,
      interactive: spec.interactive,
      command: spec.command,
      env: spec.env,
      volumes: spec.volumes,
      memory: spec.memory,
      cpus: spec.cpus,
      shmSize: spec.shmSize,
      entrypoint: spec.entrypoint,
    });
    return {
      service,
      container,
      image: spec.image,
      args,
      preview: ["wslc", ...args].map((a) => (a.includes(" ") ? JSON.stringify(a) : a)).join(" "),
    };
  });
}

/** Standard docker-compose.yaml export of the same (deployable) subset. */
export function toComposeYaml(stack: Stack): string {
  const services: Record<string, Record<string, unknown>> = {};
  for (const [service, spec] of Object.entries(stack.services)) {
    const svc: Record<string, unknown> = {
      image: spec.image,
      container_name: containerNameFor(stack.name, service),
    };
    if (spec.ports.length > 0) svc.ports = spec.ports;
    // compose runs `entrypoint` then `command` — the same argv wslc builds from
    // `--entrypoint <exe>` plus the positional command, so the export round-trips.
    if (spec.entrypoint) svc.entrypoint = spec.entrypoint;
    if (spec.command.length > 0) svc.command = spec.command;
    if (spec.env.length > 0) svc.environment = spec.env;
    if (spec.volumes.length > 0) svc.volumes = spec.volumes;
    if (spec.memory) svc.mem_limit = spec.memory;
    if (spec.cpus) svc.cpus = Number(spec.cpus);
    if (spec.shmSize) svc.shm_size = spec.shmSize;
    services[service] = svc;
  }
  return `# Generated by wslc-gui from stack "${stack.name}"\n# Deployable subset only (ports/entrypoint/command/env/volumes/limits/container_name)\n` +
    yamlStringify({ name: stack.name, services });
}
